In [2]:
import numpy as np #importing all the required libraries
import seaborn as sns
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
%matplotlib inline

C:\Users\deepa\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\deepa\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
iris = load_iris()

In [24]:
X = iris.data #specifying our data and target variables that we will be using
y = iris.target

In [81]:
iris #taking a look at how the data looks, the data should contain for columns of features and one column that contains our target

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [25]:
X #this is our data variable /features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [26]:
y #this is our target variable

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [27]:
non_versicolor_labels = [0 for i in range(100)] #relabeling to check if the species is versicolor or not
versicolor_labels = [1 for i in range(50)]

In [28]:
y = np.concatenate([non_versicolor_labels,versicolor_labels])

In [29]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
perm = np.random.permutation(150) #to make random permutation for indexing our data

In [40]:
x_train = X[perm][20:] #spliiting our data into training and testing sets
x_test = X[perm][:20]
y_train = y[perm][20:]
y_test = y[perm][0:20]

In [44]:
x_train.shape ,x_test.shape , y_test.shape , y_train.shape

((130, 4), (20, 4), (20,), (130,))

In [45]:
y_train = y_train.reshape(-1,1) #reshaping our data
y_test = y_test.reshape(-1,1) 

In [48]:
x_train = x_train[:,2:] #picking two features from our training and testing set
x_test = x_test[:,2:]

In [52]:
def sigmoid(Z): #our sigmoid function
    return 1/(1 + np.exp(-Z))

In [58]:
def logistic_loss(y,y_hat): #finding our loss
    return -np.mean(y * np.log(y_hat) + (1-y) * np.log(1 - y_hat))

In [61]:
w = np.zeros((2,1)) #we are using two features hence two weights
b = np.zeros((1,1)) #there is only one bias in this problem
learning_rate = 0.01 #defining our learning rate

In [63]:
m = len(y_train) #this will be used as the total number of samples and will help in averaging our dataset
for epochs in range(5000): #loop that runs for 5000 iterations
    Z = np.matmul(x_train,w) + b #this is our linear equation , this is now a 1 x 150 matrix
    A = sigmoid(Z) #we pass our above matrix into the sigmoid function to get another matrix of 1 x 150
    loss = logistic_loss(y_train , A) #calculating the loss
    dz = A - y_train #derivative of Z
    dw = 1/m * np.matmul(x_train.T,dz) #the derivative of w.r.t our loss
    db = np.sum(dz) #the derivative of b w.r.t our loss
    w = w - learning_rate * dw #updating our weights
    b = b - learning_rate * db #updating our bias
    
    if epochs%100 == 0:
        print(loss) #printing out the loss after 100 steps, we should probably see a decline in values

0.11216594376328543
0.11135262945593954
0.11056263289810608
0.10979489949644727
0.10904843930875631
0.10832232207148824
0.10761567268535749
0.10692766710999209
0.10625752862459208
0.10560452441668895
0.1049679624655641
0.10434718869075921
0.10374158433948029
0.10315056358964289
0.10257357134787622
0.10201008122405973
0.10145959366594368
0.10092163423914982
0.10039575203938123
0.09988151822502829
0.0993785246595572
0.09888638265413134
0.09840472180186126
0.09793318889591685
0.09747144692448655
0.09701917413623365
0.09657606317049768
0.09614182024702289
0.09571616441047297
0.09529882682542247
0.09488955011789921
0.09448808775990153
0.09409420349362405
0.0937076707924118
0.09332827235571259
0.09295579963553369
0.09259005239211215
0.09223083827670123
0.09187797243954554
0.0915312771612733
0.09119058150607579
0.09085572099517505
0.09052653729919621
0.09020287794816871
0.08988459605798028
0.08957155007219518
0.08926360351823025
0.08896062477696047
0.08866248686488788
0.08836906722807927


In [66]:
w , b #checking our weights and bias

(array([[3.52944325],
        [2.34925475]]),
 array([[-21.50548746]]))

In [69]:
preds = []  #making predictions
for i in sigmoid(Z):
    if i > 0.5:
        preds.append(1)
    else:
        preds.append(0) 

In [70]:
print(preds) #these are the predictions that we made on our training dataset

[0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0]


In [71]:
from sklearn.metrics import accuracy_score

In [74]:
accuracy_score(preds,y_train) #calculating the accuracy

0.9769230769230769

In [75]:
test_preds = [] #making predictions for our testing dataset
for i in sigmoid(Z):
    if i > 0.5:
        test_preds.append(1)
    else:
        test_preds.append(0)

In [76]:
print(test_preds)

[0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0]


In [83]:
accuracy_score(test_preds,y_train) #printig the accuracy score for testing dataset

0.9769230769230769